version: 2

jobs:
  run_apex_tests:
    docker:
      - image: jeslorlu/sfdxci:v2
    steps:
      - checkout
      - run:
          name: login into devhub
          command: |
             mkdir keys
             echo $HUB_SERVER_KEY_HEX | xxd -r -ps >> keys/hub.key
             openssl rsa -in keys/hub.key -check -noout
             sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile keys/hub.key --username $HUB_SFDC_USER --setdefaultdevhubusername -a hub
      - run:
          name: create scratch org
          command:
            sfdx force:org:create -s -f config/project-scratch-def.json -a circle_build_$circle_build_num
      - run:
            name: install lightning tests
            command:
              sfdx force:lightning:test:install -u circle_build_$circle_build_num
      - run:
          name: push source to scratch org
          command:
            sfdx force:source:push -u circle_build_$circle_build_num
      - run:
          name: run apex tests
          command: |
            mkdir -p tests/junit
            sfdx force:apex:test:run -d tests/junit -r junit
      - run:
          name: run lightning tests
          command: |
            mkdir -p uitestconfig
#            echo '{"drivers":{"chrome":{"version":2.33,"arch":"x64","baseURL":"https://chromedriver.storage.googleapis.com"}},"requestOpts":{"timeout":100000},"webdriverio":{"desiredCapabilities":{"browserName":"chrome","chromeOptions":{"args":["--headless","--disable-gpu","--no-sandbox"]}}}}' | python -mjson.tool >> uitestconfig/lts-config.json
            echo "{"drivers":{"chrome":{"version":2.33,"arch":"x64","baseURL":"https://chromedriver.storage.googleapis.com"}},"requestOpts":{"timeout":100000},"webdriverio":{"desiredCapabilities":{"browserName":"chrome","chromeOptions":{"args":["--headless","--disable-gpu","--no-sandbox"]}}}}" >> uitestconfig/lts-config.json
            mkdir -p tests/uitests
            sfdx force:lightning:test:run -f ./uitestconfig/lts-config.json -d tests/uitests -r human -a UiTestApp.app -u circle_build_$circle_build_num
      - store_test_results:
          path: tests/junit
          path: tests/uitests
      - store_artifacts:
          path: tests/junit
          path: tests/uitests
      - run:
          name: delete scratch org
          when: always
          command: |
            sfdx force:org:delete -u circle_build_$circle_build_num -p
          when: always
workflows:
  version: 2
  apex_tests:
    jobs:
      - run_apex_tests